AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-example
  Sample SAM Template for sam-example

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 30
    Handler: index.handler
    Environment:
      Variables:
        ENV_NAME: !Ref Environment
        ENV_TABLE_NAME: data-table

Resources:
  GreetingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/greeting/
      Events:
        Greeting:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /greeting
            Method: GET
      Layers:
        - !Ref SharedInternalModules

  SharedInternalModules:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedInternalModules
      ContentUri: layers/shared-internal-modules/
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GreetingApi:
    Description: 'API Gateway endpoint URL for test stage for Greeting function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/test/greeting/'
  GreetingFunction:
    Description: 'Greeting Lambda Function ARN'
    Value: !GetAtt GreetingFunction.Arn
  GreetingFunctionIamRole:
    Description: 'Implicit IAM Role created for Greeting function'
    Value: !GetAtt GreetingFunctionRole.Arn
